sudo: false

language: python

matrix:
  include:
  - python: 2.7
    env: TOXENV=py27-tests
  - python: 2.7
    env: TOXENV=py27-pyflakes
  - python: 3.4
    env: TOXENV=py34-tests
  - python: 3.4
    env: TOXENV=py34-pyflakes

install:
- pip install tox
- python setup.py install

script:
- tox
- tests/shelltests.sh
